version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:4
    ports:
      - 27017:27017
  back_node:
    container_name: back_node
    build: './API/'
    ports:
      - 3001:3001
    links:
      - mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: rootpass
  front_node:
    container_name: front_node
    build: './web/'
    ports:
      - 8080:8080
    links:
      - back_node
